# Generated by Django 5.0 on 2024-04-09 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/bus')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/bus')),
                ('total', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Packager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/packagers')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/packages')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/packages')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/packages')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/packages')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdf/packages')),
                ('packager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tourpackageapp.packager')),
            ],
        ),
    ]
