# Generated by Django 5.1.7 on 2025-03-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourpackageapp', '0002_remove_bus_available_remove_bus_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
